routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

//Frontrend
use App\Http\Controllers\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('user/create', [ HomeController::class, 'create' ]);

Route::resource('/',FrontendController::class);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('hei',function(){
    return view('halo');
});

use App\Http\Controllers\ProvinsiController;
Route::resource('provinsi',ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('kota',KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('kecamatan',KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('kelurahan',KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('rw',RwController::class);

use App\Http\Controllers\KasusController;
Route::resource('kasus',KasusController::class);




Route::get('admin', [App\Http\Controllers\HomeController::class,'admin']);
//Route::get('logout', [App\Http\Controllers\HomeController::class,'admin']);
//Frontend

app/Models/Kasus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kasus extends Model
{
    use HasFactory;

    protected $fillable = ['id_rw', 'jumlah_positif', 'jumlah_meninggal', 'jumlah_sembuh', 'tanggal'];
    protected $table = "kasuses";
    public $timestamps = true;

    public function rw(){
        return $this->belongsTo('App\Models\Rw', 'id_rw');
}
}

app/Models/Kasuss.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kasuss extends Model
{
    use HasFactory;

    protected $table = "kasusses";

    public function negara(){
        return $this->belongsTo(Negara::class);
    }
}

app/Http/Controllers/KasusController.php
<?php

namespace App\Http\Controllers;
use App\Models\Kasus;
use App\Models\Rw;
use App\Http\Controllers\DB;
use Illuminate\Http\Request;

class KasusController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); 
    }

    public function index()
    {
        $kasus = Kasus::with('rw.kelurahan.kecamatan.kota.provinsi')->get();
        return view('kasus.index',compact('kasus'));
    }

   
    public function create()
    {
       $rw = Rw::all();
       return view('kasus.create',compact('rw'));
    }

    
    public function store(Request $request)
    {
          $request->validate([
            'jumlah_positif' => 'required',
            'jumlah_meninggal' => 'required',
            'jumlah_sembuh' => 'required',
            'tanggal' => 'required',
          ],[
            'jumlah_positif.required' => 'Jumlah Positif required',
            'jumlah_meninggal.required' => 'Jumlah Positif required',
            'jumlah_sembuh.required' => 'Jumlah Positif required',
            'tanggal.required' => 'Tanggal required',

          ]);

    $kasus = new Kasus();
    $kasus->id_rw            = $request->id_rw;
    $kasus->jumlah_positif   = $request->jumlah_positif;
    $kasus->jumlah_meninggal = $request->jumlah_meninggal;
    $kasus->jumlah_sembuh    = $request->jumlah_sembuh;
    $kasus->tanggal          = $request->tanggal;
    $kasus->save();
    return redirect()->route('kasus.index');
        
    }

   
    public function show($id)
    {
        $kasus = Kasus::FindOrFail($id);
        return view('kasus.show',compact('kasus'));
    }

    public function edit($id)
    {
      $kasus = Kasus::FindOrFail($id);
      $rw = Rw::all();
      return view('kasus.edit',compact('rw','kasus'));
    }

    
    public function update(Request $request, $id)
    {

      $request->validate([
        'jumlah_positif' => 'required',
        'jumlah_meninggal' => 'required',
        'jumlah_sembuh' => 'required',
        'tanggal' => 'required',
      ],[
        'jumlah_positif.required' => 'Jumlah Positif required',
        'jumlah_meninggal.required' => 'Jumlah Positif required',
        'jumlah_sembuh.required' => 'Jumlah Positif required',
        'tanggal.required' => 'Tanggal required',

      ]);
      
    $kasus = Kasus::FindOrFail($id);
    $kasus->id_rw            = $request->id_rw;
    $kasus->jumlah_positif   = $request->jumlah_positif;
    $kasus->jumlah_meninggal = $request->jumlah_meninggal;
    $kasus->jumlah_sembuh    = $request->jumlah_sembuh;
    $kasus->tanggal          = $request->tanggal;
    $kasus->save();
    return redirect()->route('kasus.index');
        
    }
   
    public function destroy($id)
    {
      $kasus = Kasus::FindOrFail($id)->delete();
      return redirect()->route('kasus.index');
    }
}

resources/views/kasus/create.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Tambah Data Kasus
                </div>
                <div class="card">
                <div class="card-body" >
                <form  action="{{route('kasus.store')}}" method="post">
                  @csrf
                    @livewireStyles

                      @livewire('covid')

                      @livewireScripts
                      
                      <div class="form-group">
                          <label for="">Positif</label>
                          <input type="text" name="jumlah_positif" class="form-control" required>
                          @if ($errors->has('jumlah_positif'))
                          <span class="text-danger">{{ $errors->first('jumlah_positif') }}</span>
                      @endif 
                        </div>
                      <div class="form-group">
                        <label for="">Meninggal</label>
                        <input type="text" name="jumlah_meninggal" class="form-control" required>
                        @if ($errors->has('jumlah_meninggal'))
                        <span class="text-danger">{{ $errors->first('jumlah_meninggal') }}</span>
                    @endif 
                </div>
                    <div class="form-group">
                        <label for="">Sembuh</label>
                        <input type="text" name="jumlah_sembuh" class="form-control" required>
                        @if ($errors->has('jumlah_sembuh'))
                        <span class="text-danger">{{ $errors->first('jumlah_sembuh') }}</span>
                    @endif 
                    </div>
                    <div class="form-group">
                        <label for="">Tanggal</label>
                        <input type="date" name="tanggal" class="form-control" required>
                        @if ($errors->has('tanggal'))
                        <span class="text-danger">{{ $errors->first('tanggal') }}</span>
                    @endif 
                    </div>
                    <div class="form-group">
                    <button type="submit" class="for fa-save btn btn-outline-primary float-right">Simpan</button>
                    </div>
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kasus/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit Data Kasus 
                </div>
                <div class="card">
                <div class="card-body" >
                <form  action="{{route('kasus.update',$kasus->id)}}" method="post">
                    @csrf
                    @livewireStyles

                    @livewireScripts
                      @method('PUT')
                     <div>
                         @livewire('covid',['selectedState5' => $kasus->id_rw])
                     </div>

                      <div class="form-group">
                        <label for="">Positif</label>
                        <input type="text" name="jumlah_positif" value="{{$kasus->jumlah_positif}}" class="form-control" required>
                        @if ($errors->has('jumlah_positif'))
                        <span class="text-danger">{{ $errors->first('jumlah_positif') }}</span>
                    @endif 
                    </div>
                     <div class="form-group">
                        <label for="">Meninggal</label>
                        <input type="text" name="jumlah_meninggal" value="{{$kasus->jumlah_meninggal}}" class="form-control" required>
                        @if ($errors->has('jumlah_meninggal'))
                        <span class="text-danger">{{ $errors->first('jumlah_meninggal') }}</span>
                    @endif  
                    </div>
                     <div class="form-group">
                        <label for="">Sembuh</label>
                        <input type="text" name="jumlah_sembuh" value="{{$kasus->jumlah_sembuh}}" class="form-contro" required>
                        @if ($errors->has('jumlah_sembuh'))
                        <span class="text-danger">{{ $errors->first('jumlah_sembuh') }}</span>
                    @endif 
                    </div>
                     <div class="form-group">
                        <label for="">Tanggal</label>
                        <input type="date" name="tanggal" value="{{$kasus->tanggal}}" class="form-control" required>
                        @if ($errors->has('tanggal'))
                        <span class="text-danger">{{ $errors->first('tanggal') }}</span>
                    @endif 
                    </div>
                    <div class="form-group"> 
                        <button type="submit" class="btn btn-success">Ubah</button>
                        <a href="{{url()->previous()}}" class="btn btn-outline-info">Kembali</a>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kasus/index.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Kasus') }} 
                </div>
                
                <div class="card">
                <a href="{{route('kasus.create')}}" class="btn btn-primary float-right"> Add Data </a>

                <div class="card-body" >
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                            
                        </div>
                    @endif
                    <table class="table table-dark table-hover">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Lokasi</th>
                                    <th>Rw</th>
                                    <th>Positif</th>
                                    <th>Meninggal</th>
                                    <th>Sembuh</th>
                                    <th>Tanggal</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no=1; @endphp
                                @foreach($kasus as $data)
                                <tr>
                                    <td>{{$no++}}</td>
                                    <td>
                                        Kelurahan : {{$data->rw->kelurahan->nama_kelurahan}}<br>
                                        Kecamatan : {{$data->rw->kelurahan->kecamatan->nama_kecamatan}}<br>
                                        Kota : {{$data->rw->kelurahan->kecamatan->kota->nama_kota}}<br>
                                        Provinsi : {{$data->rw->kelurahan->kecamatan->kota->provinsi->nama_provinsi}}
                                    </td>
                                    <td>{{$data->rw->rw}}</td>
                                    <td>{{$data->jumlah_positif}}</td>
                                    <td>{{$data->jumlah_meninggal}}</td>
                                    <td>{{$data->jumlah_sembuh}}</td>
                                    <td>{{$data->tanggal}}</td>
                                    <td>
                                        <form action="{{route('kasus.destroy',$data->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{route('kasus.show',$data->id)}}" class="btn btn-sm btn-success">Show</a> |
                                            <a href="{{route('kasus.edit',$data->id)}}" class="btn btn-sm btn-warning">Update</a> |
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Apakah Anda Yakin ?')">
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kasus/show.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Data Rw') }} 
                </div>
                
                <div class="card">
             

                <div class="card-body">
                     <div class="form-group">
                        <label for="">RW</label>
                        <input type="text" name="id_rw" class="form-control" value="{{$kasus->rw->rw}}" value="{{'kasuse->nama_rw'}}"readonly>
                    </div>
                      <div class="form-group">
                    <div class="mb-12>
                        <label for="exampleInputPassword1" class="form-label">Positif</label>
                        <input type="number" class="form-control" id="exampleInputPassword1" name="jumlah_positif"
                         value="{{$kasus->jumlah_positif}}"readonly>
                    </div>
                     </div>
                     <div class="form-group">
                    <div class="mb-12>
                        <label for="exampleInputPassword1" class="form-label">Meninggal</label>
                        <input type="number" class="form-control" id="exampleInputPassword1" name="jumlah_meninggal"
                        value="{{$kasus->jumlah_meninggal}}" readonly>
                    </div>
                     </div>
                     <div class="form-group">
                    <div class="mb-12>
                        <label for="exampleInputPassword1" class="form-label">Sembuh</label>
                        <input type="number" class="form-control" id="exampleInputPassword1" name="jumlah_sembuh"
                        value="{{$kasus->jumlah_sembuh}}" readonly>
                    </div>
                     </div>
                     <div class="form-group">
                    <div class="mb-12>
                        <label for="exampleInputPassword1" class="form-label">Tanggal</label>
                        <input type="date" class="form-control" id="exampleInputPassword1" name="tanggal"
                        value="{{$kasus->tanggal}}" readonly>
                    </div>
                     </div>
                   
                     <a href="{{ url()->previous() }}" class="btn btn-primary">Back</a></button>

                </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection