routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

//Frontrend
use App\Http\Controllers\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('user/create', [ HomeController::class, 'create' ]);

Route::resource('/',FrontendController::class);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('hei',function(){
    return view('halo');
});

use App\Http\Controllers\ProvinsiController;
Route::resource('provinsi',ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('kota',KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('kecamatan',KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('kelurahan',KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('rw',RwController::class);

use App\Http\Controllers\KasusController;
Route::resource('kasus',KasusController::class);




Route::get('admin', [App\Http\Controllers\HomeController::class,'admin']);
//Route::get('logout', [App\Http\Controllers\HomeController::class,'admin']);
//Frontend

app/Models/Provinsi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Provinsi extends Model
{
    use HasFactory;

    protected $fillable = ['kode_provinsi','nama_provinsi'];
    public $timestamps = true;

    protected $table = "provinsis";

    public function kota(){
        return $this->hasMany(Kota::class);
    }
}

app/Http/Controllers/Api/ProvinsiController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Provinsi;

class ProvinsiController extends Controller
{

    
    public function index()
    {
        
        $provinsi = Provinsi::latest()->get();
        $res = [
            'success' => true,
            'data'    => $provinsi,
            'message' => 'Data Berhasil Di Tampilkan'   
        ];
        return response()->json($res,200);

    }

    
    public function create()
    {
        //
    }

   
    public function store(Request $request)
    {
        //
    }

    
    public function show($id)
    {
        $provinsi = Provinsi::whereId($id)->first();

        if($provinsi) {
            return response()->json([
                'success' => true,
                'message' => 'Detail Provinsi',
                'data' => $provinsi
            ], 200);
        } else {
            return response()->json([
                'success' => false,
                'message' => 'Provinsi Tidak Ditemukan',
                'data' => ''
            ], 404);
        }
    }

    
    public function edit($id)
    {
        //
    }

   
    public function update(Request $request, $id)
    {
        //
    }

   
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ProvinsiController.php
<?php

namespace App\Http\Controllers;
use App\Models\Provinsi;
use App\Http\Controllers\DB;
use Illuminate\Http\Request;
// use Validator;

class ProvinsiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $provinsi = Provinsi::all();
        return view('provinsi.index', compact('provinsi'));
    }

    
    public function create()
    {
        return view('provinsi.create');
    }

    
    public function store(Request $request)
    {
       //VALIDASI
       $request->validate([
           'kode_provinsi' => 'required|max:4|unique:provinsis',
           'nama_provinsi' => 'required|unique:provinsis',
       ], [
           'kode_provinsi.required' => 'Kode Harus Di isi!',
           'kode_provinsi.max' =>  'Kode Maksimal 4 Nomor',
           'kode_provinsi.unique' => 'Kode Sudah Dipakai',
           'nama_provinsi.required' => 'Nama Provinsi Harus Di Isi!',
           'nama_provinsi.unique' => 'Kode Sudah Di Pakai!',
       ]);
            
        $provinsi = new Provinsi;
        $provinsi->kode_provinsi = $request->kode_provinsi;
        $provinsi->nama_provinsi = $request->nama_provinsi;
        $provinsi->save();
        return redirect()->route('provinsi.index');

    }

    public function show($id){
        $provinsi = Provinsi::findOrFail($id);
        return view('provinsi.show',compact('provinsi'));
    }
    

    public function edit($id)
    {
        $provinsi = Provinsi::findOrFail($id);
        return view('provinsi.edit',compact('provinsi'));

    }

    
    public function update(Request $request, $id)
    {
        $provinsi = Provinsi::FindOrFail($id);
        $provinsi->kode_provinsi = $request->kode_provinsi;
        $provinsi->nama_provinsi = $request->nama_provinsi;
        $provinsi->save();
        return redirect()->route('provinsi.index')->with(['message'=>'provinsi berhasil di edit']);
    }

    
    public function destroy($id)
    {
        $provinsi = Provinsi::FindOrFail($id)->delete();
        return redirect()->route('provinsi.index')->with(['message'=>'provinsi berhasil di hapus']);
    }
}

resources/views/provinsi/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Menampilkan Data Provinsi</div>
                <div class="card-body">
                   <!--FORM INPUT PROVINSI -->

                  <form action="{{route('provinsi.store')}}" method="POST">
                        @csrf
                        <div class="mb-3">
                          <label for="">Kode Provinsi</label>
                          <input type="text" name="kode_provinsi" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">    
                          @if ($errors->has('kode_provinsi'))
                              <span class="text-danger">{{ $errors->first('kode_provinsi') }}</span>
                          @endif
                       </div>

                       <div class="mb-3">
                          <label for="">Nama Provinsi</label>
                          <input type="text"  name="nama_provinsi" class="form-control" id="exampleInputPassword1">
                          @if ($errors->has('nama_provinsi'))
                          <span class="text-danger">{{ $errors->first('nama_provinsi') }}</span>
                      @endif
                      </div>
                        <button type="submit" class="btn btn-primary">Add Data</button>
                      </form>
                    

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/provinsi/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Menampilkan Data Edit Provinsi</div>
                <div class="card-body">
                   <!--FORM INPUT PROVINSI -->

                  <form action="{{route('provinsi.update',$provinsi->id)}}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                          <label for="exampleInputEmail1" class="form-label">Kode Provinsi</label>
                          <input type="text" name="kode_provinsi" value="{{$provinsi->kode_provinsi}}"class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">    

                       </div>
                       <div class="mb-3">
                          <label for="exampleInputPassword1" class="form-label">Nama Provinsi</label>
                          <input type="text"  name="nama_provinsi"  value="{{$provinsi->nama_provinsi}}"class="form-control" id="exampleInputPassword1">

                      </div>
                        <button type="submit" class="btn btn-primary">Edit Data</button>
                      </form>
                    

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/provinsi/index.blade.php
              @extends('layouts.master')

              @section('content')
              <div class="container">
                  <div class="row justify-content-center">
                      <div class="col-md-8">
                          <div class="card">
                              <div class="card-header">Dashboard</div>

                              <div class="card-body">
                                
                                <a href="{{route('provinsi.create')}}" class="btn btn-outline-success float-right"><b>Add Data</b></a>
                                
                                  <table class="table">
                <thead>
                  <tr>
                    <th scope="col">No</th>
                    <th scope="col">Kode Provinsi</th>
                    <th scope="col">Provinsi</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                @php $no = 1; @endphp
                @foreach ($provinsi as $data)
                  <tr>
                    <td>{{ $no++ }}</td>
                    <td>{{$data->kode_provinsi}} </td>
                    <td>{{$data->nama_provinsi}} </td>
                    <td>
                      
                    <form action="{{route('provinsi.destroy', $data->id)}}" method="post">
                    @csrf
                    @method("DELETE")
                    <a href="{{ route('provinsi.show', $data->id) }}" class="btn btn-outline-primary">Show</a> 
                    <a href="{{ route('provinsi.edit', $data->id) }}"class="btn btn-outline-success">Edit</a>
                    <button  type="submit" onclick="return confirm('Apakah Anda Yakin?')" class="btn btn-outline-danger">Delete</button>
                    </td>

                  </tr>
                  </form>
                  @endforeach
                  <tr>
                    <th scope="row"></th>
                  </tr>
                  <tr>
                    <th scope="row"></th>
                  </tr>
                </tbody>
              </table>

                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              @endsection

resources/views/provinsi/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Menampilkan Data Provinsi</div>
                <div class="card-body">
                        @csrf
                        <div class="mb-3">
                          <label for="">Kode Provinsi</label>
                          <input type="text" name="kode_provinsi" value="{{$provinsi->kode_provinsi}}" class="form-control" readonly>
                       </div>
                       <div class="mb-3">
                        <label for="">Nama Provinsi</label>
                        <input type="text" name="nama_provinsi" value="{{$provinsi->nama_provinsi}}" class="form-control" readonly>
                      </div>
                        <a href="{{url()->previous()}}" class="btn btn-outline-secondary">Kembali</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection