routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

//Frontrend
use App\Http\Controllers\FrontendController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('user/create', [ HomeController::class, 'create' ]);

Route::resource('/',FrontendController::class);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('hei',function(){
    return view('halo');
});

use App\Http\Controllers\ProvinsiController;
Route::resource('provinsi',ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('kota',KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('kecamatan',KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('kelurahan',KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('rw',RwController::class);

use App\Http\Controllers\KasusController;
Route::resource('kasus',KasusController::class);




Route::get('admin', [App\Http\Controllers\HomeController::class,'admin']);
//Route::get('logout', [App\Http\Controllers\HomeController::class,'admin']);
//Frontend

app/Models/Kelurahan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelurahan extends Model
{
    protected $fillable = ['id_kecamatan','nama_kelurahan'];
    protected $table = "kelurahans";


     public function kecamatan(){
        return $this->belongsTo('App\Models\Kecamatan', 'id_kecamatan');
    }

    public function rw(){
        return $this->hasMany('App\Models\Rw', 'id_kelurahan');
    }
    
    use HasFactory;
}


     
     
    
    
     
    

app/Http/Controllers/KelurahanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelurahan;
use App\Models\Kecamatan;
use Illuminate\Http\Request;

class KelurahanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth'); 
    }

  
    public function index()
    {
        $kelurahan = Kelurahan::with('kecamatan')->get();
        return view('kelurahan.index',compact('kelurahan'));
    }

    
    public function create()
    {
        $kecamatan = Kecamatan::all();
        return view('kelurahan.create',compact('kecamatan'));
    }


    public function store(Request $request)
    {

        //VALIDASI
       $request->validate([
        'nama_kelurahan' => 'required|max:4|unique:kelurahans',
        'nama_kelurahan' => 'required|unique:kelurahans',
    ], [
        'nama_kelurahan.required' => 'Kode Harus Di isi!',
        'nama_kelurahan.max' =>  'Kode Maksimal 4 Nomor',
        'nama_kelurahan.unique' => 'Kode Sudah Dipakai',
        'nama_kecamatan.required' => 'Nama Provinsi Harus Di Isi!',
        'nama_kecamatan.unique' => 'Nama Sudah Di Pakai!',
    ]);
        $kelurahan = new Kelurahan; 
        $kelurahan->nama_kelurahan = $request->nama_kelurahan;  
        $kelurahan->id_kecamatan= $request->id_kecamatan; 
        $kelurahan->save();
        return redirect()->route('kelurahan.index')->with(['message'=>'Data Berhasil Dibuat']);
    }


    public function show($id)
    {
        $kelurahan = Kelurahan::FindOrFail($id);
        return view('kelurahan.show',compact('kelurahan'));
    }

    public function edit($id)
    {
        $kelurahan = Kelurahan::FindOrFail($id);
        $kecamatan = Kecamatan::all();
        return view('kelurahan.edit',compact('kelurahan','kecamatan'));
    }

    public function update(Request $request, $id)
    {
        $kelurahan = Kelurahan::FindOrFail($id);
        $kelurahan->nama_kelurahan = $request->nama_kelurahan;
        $kelurahan->id_kecamatan = $request->id_kecamatan;        
        $kelurahan->save();
        return redirect()->route('kelurahan.index')->with(['message'=>'Data Berhasil Diedit']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Kelurahan  $kelurahan
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kelurahan= Kelurahan::FindOrFail($id)->delete();
        return redirect()->route('kelurahan.index')->with(['message'=>'kota berhasil dihapus']);
    }
}

resources/views/kelurahan/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Data Kelurahan</div>
                   <div class="card-body">
                       <form action="{{route('kelurahan.store')}}" method="POST">
                          @csrf
                         <div class="mb-3">
                            <label for="">Nama Kelurahan</label>
                            <input type="text" name="nama_kelurahan" class="form-control">       
                            @if ($errors->has('nama_kelurahan'))
                            <span class="text-danger">{{ $errors->first('nama_kelurahan') }}</span>
                        @endif 
                        </div>
                         <div class="mb-3">
                            <label for="">Nama Kecamatan</label>
                            <select class="form-control" name="id_kecamatan" id="">
                                @if ($errors->has('nama_kecamatan'))
                              <span class="text-danger">{{ $errors->first('nama_kecamatan') }}</span>
                          @endif
                                @foreach ($kecamatan as $data)
                                     <option value="{{$data->id}}">{{$data->nama_kecamatan}}</option>   
                                @endforeach
                            </select>
                         </div>
                         <div class="form-group">
                              <button type="submit" class="btn btn-outline-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelurahan/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Menampilkan Data Edit Kelurahan</div>
                   <div class="form-group">
                      <form action="{{route('kelurahan.update',$kelurahan->id)}}" method="POST">
                        <!-- <input type="hidden" name="_method" value="PUT"> -->
                          @csrf
                          @method('PUT')
                         <div class="form-group">
                              <label for="">Nama Kelurahan</label>
                              <input type="text"  name="nama_kelurahan"  value="{{$kelurahan->nama_kelurahan}}"class="form-control" required>  
                         </div>
                         <div class="form-group">
                              <label for="exampleFormControlSelect1">Kecamatan</label>
                              <select class="form-control" name="id_kecamatan" id="exampleFormControlSelect1">
                                  @foreach ($kecamatan as $data)
                                      <option value="{{$data->id}}"
                                        @if($data->nama_kecamatan == $kelurahan->kecamatan->nama_kecamatan)
                                        selected
                                        @endif
                                        >
                                        {{$data->nama_kecamatan}}
                                      </option>
                                  @endforeach
                           </select>
                           <div class="form-group">
                                <button type="submit" class="btn btn-outline-primary">Edit</button>
                                <a href="{{url()->previous()}}" class="btn btn-outline-secondary">Kembali</a>
                           </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelurahan/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                  Data Kelurahan
                  <a href="{{route('kelurahan.create')}}" class="btn btn-outline-success float-right">
                    Add Data
                  </a>
                </div>
                  <div class="card-body">
                    <div class="table-responsive">
                       <table class="table">
                         <thead>
                      <tr>
                            <th>No</th>
                            <th>Nama Kelurahan</th>
                            <th>Nama Kecamatan</th>
                            <th>Action</th>
                      </tr>
                  </thead>
                   <tbody>
                        @php $no = 1; @endphp
                        @foreach ($kelurahan as $data)
                        <tr>
                            <td>{{ $no++}}</td>
                            <td>{{$data->nama_kelurahan}}</td>
                            <td>{{$data->kecamatan->nama_kecamatan}}</td>
                            <td>
                                  
                                    <form action="{{route('kelurahan.destroy', $data->id)}}" method="post">
                                        @csrf
                                        @method("DELETE")
                                        <a href="{{ route('kelurahan.show', $data->id) }}" class="btn btn-outline-primary">Show</a> 
                                        <a href="{{ route('kelurahan.edit', $data->id) }}"class="btn btn-outline-success">Edit</a>
                                        <button  type="submit" onclick="return confirm('Apakah Anda Yakin?')" class="btn btn-outline-danger">Delete</button>
                                    </form>
                              </td>
                            </tr>
                              @endforeach
                        </tbody>  
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kelurahan/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Menampilkan Data Kelurahan</div>
                <div class="card-body">
                        @csrf
                       <div class="form-group">
                               <label for="">Nama Kelurahan</label>
                               <input type="text" name="nama_kelurahan" value="{{$kelurahan->nama_kelurahan}}" class="form-control" readonly>
                       </div>
                       <div class="form-group">
                               <label for="">Nama Kecamatan</label>
                               <input type="text" name="id_kecamatan" value="{{$kelurahan->kecamatan->nama_kecamatan}}" class="form-control" readonly>
                       </div>
                       <div class="form-group">
                        <a href="{{url()->previous()}}" class="btn btn-outline-secondary">Kembali</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection